language: python
sudo: false
python:
    - pypy
    - 2.6
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3
install:
    - pip install pytest flake8 check-manifest
script:
    - ./run-tests.sh
